name: firstuse_parking_app
description: "Overnight car parking app built with Flutter."
publish_to: 'none'
version: 0.1.0

# added necessary packages
# reactive forms
# geolocation api
# sqflit db


environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  reactive_forms: ^17.0.1
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.0.0
  google_maps_flutter: ^2.1.1
  geocoding: ^2.0.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/minimalcar.png
